export default  {
    menulist:[
        {
            title:'首页',
            icon:'home',
            url:'/'
        },
        {
            title:'异常页面',
            icon:'tag',
            children:[
                {
                    title:'404',
                    icon:'tag',
                    url:'/page/404',
                },
                {
                    title:'500',
                    icon:'tag',
                    url:'/page/500',
                }
            ]
        },
        {
            title:'菜单2',
            icon:'tag',
            children:[
                {
                    title:'子菜单3',
                    icon:'tag',
                    url:'/menu3',
                },
                {
                    title:'子菜单4',
                    icon:'tag',
                    url:'/menu4',
                }
            ]
        }
    ],
};